### PR TITLE
Add BG6HJE and BG6HJE/9 please

### PR DESCRIPTION
**Pull request by BG6HJE-edu**
Thanks a lot! 73 from China, DE BG6HJE!

### CODE REVIEW

**Comment by AndreasK79** [comment]
You are welcome! Let us know if it doesn't work, or if you have some feaure requests for the map.

**Comment by BG6HJE-edu** [comment]
The website seems to be experiencing some issues. I first accessed "https://images.wavelog.org/img/map?call=BG6HJE" and received a "Not Registered" message. Then I tried "https://images.wavelog.org/img/map?call=DF2ET" again and got the same message. Additionally, when I visited "https://qrz.com/db/DF2ET", the image on the homepage also failed to display.
Screenshot_1
Screenshot_2

**Comment by AndreasK79** [comment]
I suspect it didn't like the / in the callsign, so I replaced it with -. Not sure if that fixes it. If not, we need to wait for @int2001 to look into it.

**Comment by BG6HJE-edu** [comment]
It seems it was a false alarm; the images are now being retrieved correctly.
map

**Comment by AndreasK79** [comment]
@BG6HJE-edu /9 is re-added now. Need to use -9 in the callsign in the url.

**Comment by BG6HJE-edu** [comment]
@AndreasK79 Much thanks! 73.

**Pull request merged**
